# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
